DROP TABLE  BLOG_ACTIVITY_LOG1
/
DROP TABLE  BLOG_ACTIVITY_LOG2
/
DROP TABLE  BLOG_COMMENT_USER CASCADE CONSTRAINTS
/
DROP TABLE  BLOG_AUTHOR
/
DROP TABLE  BLOG_CATEGORY CASCADE CONSTRAINTS
/
DROP TABLE  BLOG_PAGE_LOG
/
DROP TABLE  BLOG_PAGE_PREVIEW
/
DROP TABLE  BLOG_CATEGORY_LOG
/
DROP TABLE  BLOG_COMMENT
/
DROP TABLE  BLOG_COMMENT_BLOCK
/
DROP TABLE  BLOG_COMMENT_NOTIFY
/
DROP TABLE  BLOG_CONTACT_MESSAGE
/
DROP TABLE  BLOG_COUNTRY
/
DROP TABLE  BLOG_FAQ
/
DROP TABLE  BLOG_PARAM CASCADE CONSTRAINTS
/
DROP table blog_email_template
/
DROP table blog_posts
/